gui:
  screenMode: half

  theme:
    selectedLineBgColor:
      - '#414559'

  authorColors:
    '*': '#bbbbbb'

git:
  log:
    showWholeGraph: true

keybinding:
  universal:
    scrollUpMain: ','
    scrollDownMain: '.'

    prevPage: '<pgup>'
    nextPage: '<pgdown>'
